"""add payment columns

Revision ID: 5492f974472c
Revises: 6cb98a317ca4
Create Date: 2026-05-28 17:02:57.740097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5492f974472c'
down_revision: Union[str, Sequence[str], None] = '6cb98a317ca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket_bookings', sa.Column('payment_status', sa.String(length=20), server_default='PENDING', nullable=False))
    op.add_column('ticket_bookings', sa.Column('razorpay_order_id', sa.String(length=255), nullable=True))
    op.add_column('ticket_bookings', sa.Column('razorpay_payment_id', sa.String(length=255), nullable=True))
    op.add_column('ticket_bookings', sa.Column('razorpay_signature', sa.String(length=500), nullable=True))
    op.create_index(op.f('ix_ticket_bookings_email'), 'ticket_bookings', ['email'], unique=False)
    op.create_index(op.f('ix_ticket_bookings_user_id'), 'ticket_bookings', ['user_id'], unique=False)
    op.create_unique_constraint(None, 'ticket_bookings', ['razorpay_payment_id'])
    op.create_unique_constraint(None, 'ticket_bookings', ['razorpay_order_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ticket_bookings', type_='unique')
    op.drop_constraint(None, 'ticket_bookings', type_='unique')
    op.drop_index(op.f('ix_ticket_bookings_user_id'), table_name='ticket_bookings')
    op.drop_index(op.f('ix_ticket_bookings_email'), table_name='ticket_bookings')
    op.drop_column('ticket_bookings', 'razorpay_signature')
    op.drop_column('ticket_bookings', 'razorpay_payment_id')
    op.drop_column('ticket_bookings', 'razorpay_order_id')
    op.drop_column('ticket_bookings', 'payment_status')
    # ### end Alembic commands ###
